### ISSUE TITLE
Crash in the first start

### ISSUE THREAD

**Issue by orafaaraujo** [phrase/android-sdk-example#8]
Hello,

I noticed a crash the first time of running the app with the SDK integrated.

When applying the call to `Phrase.wrapApplicationContext()` on `attachBaseContext`:
```
    override fun attachBaseContext(base: Context?) {
        base
            ?.let { super.attachBaseContext(Phrase.wrapApplicationContext(it)) }
            ?: run { super.attachBaseContext(base) }
    }
```

The app crashes, with the following stack:
```
E: FATAL EXCEPTION: main
    Process: com.mypackage, PID: 15357
    java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassCastException: com.phrase.android.sdk.inject.PhraseContextWrapper cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3576)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassCastException: com.phrase.android.sdk.inject.PhraseContextWrapper cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3560)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

Does the SDK have any incompatibility with Firebase? Any recommendations on that?

I also noticed that if the app doesn’t override the `attachBaseContext`,  all translations work, and no crashes are seen.

Do we really override `attachBaseContext` in our Application?

Thank you.

**Comment by theSoenke** [comment]
Hey @orafaaraujo, thanks for raising this issue. The Android SDK is casting to `ContextImpl` in certain cases internally, which is causing this exception. This issue has been fixed in version [3.0.2](https://github.com/phrase/phrase-android/releases/tag/3.0.2). Overrriding `attachBaseContext` is not necessary in all cases, but required for translations in classes not inheriting from an activity e.g. notifications.
